name: Terraform AWS S3 CloudFront

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Choose Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:

  terraform:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:

      # Checkout Repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Apply on Push OR Manual Apply
      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: |
          terraform apply -auto-approve

      # Get Terraform Outputs
      - name: Read Terraform Outputs
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: |
          echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
          echo "DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      # Upload Website Files to S3
      - name: Upload Files to S3
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: |
          aws s3 sync . s3://$BUCKET_NAME \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "*.tf" \
          --exclude "*.tfvars"

      # CloudFront Invalidation
      - name: CloudFront Invalidation
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: |
          aws cloudfront create-invalidation \
          --distribution-id $DISTRIBUTION_ID \
          --paths "/*"

      # Show final URLs
      - name: Show Deployment URLs
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: |
          echo "====================================="
          echo "🚀 DEPLOYMENT COMPLETED"
          echo "====================================="
          echo "S3 Website URL:"
          terraform output -raw s3_static_website_endpoint
      
          echo "CloudFront URL:"
          terraform output -raw cloudfront_distribution_id

          echo "Cloud Front Domain Name"
          terraform output -raw cloudfront_domain_name

          echo "====================================="

      # Terraform Destroy only Manual
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          terraform destroy -auto-approve
